"use client";
import Link from "next/link";
import { useEffect, useState } from "react";
import { api } from "./api";
import { Frame, Loading, Message } from "./screens/shared";
type Overview={metrics:{totalLeads:number;wonDeals:number;openTasks:number};stages:{status:string;count:number}[];sources:{source:string;count:number}[];recentLeads:{id:string;name:string;interest:string|null;status:string;createdAt:string}[];upcomingTasks:{id:string;title:string;dueAt:string|null;lead:{name:string}|null;customer:{name:string}|null}[]};
const friendly=(s:string)=>s.replaceAll("_"," ").toLowerCase().replace(/\b\w/g,c=>c.toUpperCase());
export default function OverviewPage(){const [overview,setOverview]=useState<Overview|null>(null);const [loading,setLoading]=useState(true);const [error,setError]=useState("");useEffect(()=>{api<Overview>("/dashboard/overview").then(setOverview).catch(e=>setError(e instanceof Error?e.message:"Could not load workspace overview.")).finally(()=>setLoading(false));},[]);
 return <Frame title="Marketing Overview" subtitle="Your workspace activity at a glance.">{error&&<Message error>{error}</Message>}{loading?<Loading/>:overview&&<><div className="metrics"><article className="metric"><div className="icon blue">♧</div><div><small>Total Leads</small><strong>{overview.metrics.totalLeads.toLocaleString()}</strong><em>Saved in this workspace</em></div></article><article className="metric"><div className="icon teal">◈</div><div><small>Won Deals</small><strong>{overview.metrics.wonDeals}</strong><em>From deal records</em></div></article><article className="metric"><div className="icon violet">☑</div><div><small>Open Tasks</small><strong>{overview.metrics.openTasks}</strong><em>Follow-ups and team work</em></div></article><article className="metric"><div className="icon amber">◎</div><div><small>Cost per Lead</small><strong>N/A</strong><em>Campaigns are part of Phase 5</em></div></article></div><div className="panels"><article className="panel"><h2>Lead Pipeline <Link href="/leads">Manage leads →</Link></h2><div className="pipeline-summary">{["NEW","CONTACTED","INTERESTED","PROPOSAL_PENDING","WON","LOST"].map(status=><div key={status}><b>{overview.stages.find(x=>x.status===status)?.count??0}</b><small>{friendly(status)}</small></div>)}</div></article><article className="panel"><h2>Lead Sources</h2>{overview.sources.length===0?<p className="subtle">Sources will appear when you add leads.</p>:<ul className="source-list">{overview.sources.map(({source,count})=><li key={source}><span>{friendly(source)}</span><b>{overview.metrics.totalLeads?Math.round(count/overview.metrics.totalLeads*100):0}%</b></li>)}</ul>}</article></div><div className="panels lower"><article className="panel"><h2>Recent Leads <Link href="/leads">View all →</Link></h2>{overview.recentLeads.map(l=><div className="simple-row" key={l.id}><b>{l.name}</b><span>{l.interest||"—"}</span><span className="badge">{friendly(l.status)}</span></div>)}{overview.recentLeads.length===0&&<p className="subtle">Your first lead will show here.</p>}</article><article className="panel"><h2>Upcoming Tasks <Link href="/tasks">View all →</Link></h2>{overview.upcomingTasks.map(t=><div className="simple-row" key={t.id}><b>{t.title}</b><span>{t.dueAt?new Date(t.dueAt).toLocaleDateString():"No date"}</span></div>)}{overview.upcomingTasks.length===0&&<p className="subtle">No open tasks right now.</p>}</article></div><p className="demo-note">Overview metrics are calculated from workspace records. Monetary campaign performance is shown after campaigns are added.</p></>}</Frame>;
}
