"use client";
import Image from "next/image";
import Link from "next/link";
import { useRouter } from "next/navigation";
import { ChangeEvent, FormEvent, useRef, useState } from "react";
import { api, Workspace } from "../api";
import { PasswordField } from "../password-field";

export default function RegisterPage() {
  const [name,setName]=useState("");const [email,setEmail]=useState("");const [password,setPassword]=useState("");const [workspaceName,setWorkspaceName]=useState("");const [countryCode,setCountryCode]=useState("+92");const [phone,setPhone]=useState("");const [profileImage,setProfileImage]=useState("");const [error,setError]=useState("");const [message,setMessage]=useState("");const [busy,setBusy]=useState(false);const fileInput=useRef<HTMLInputElement>(null);const router=useRouter();
  function selectImage(e:ChangeEvent<HTMLInputElement>){const file=e.target.files?.[0];if(!file)return;if(!["image/png","image/jpeg","image/webp"].includes(file.type)||file.size>1_000_000){setError("Choose a PNG, JPEG or WebP image under 1 MB.");e.target.value="";return;}const reader=new FileReader();reader.onload=()=>{setProfileImage(String(reader.result));setError("")};reader.onerror=()=>setError("Could not read this image.");reader.readAsDataURL(file);}
  async function submit(e:FormEvent){e.preventDefault();setError("");setMessage("");setBusy(true);try{const result=await api<{verificationUrl?:string}>("/auth/register",{method:"POST",body:JSON.stringify({name,email,password,workspaceName,phone:phone?`${countryCode} ${phone}`:undefined,profileImage:profileImage||undefined})});if(result.verificationUrl){const url=new URL(result.verificationUrl);router.replace(url.pathname+url.search);}else setMessage("Workspace created. Check your email for the verification link.");}catch(e){setError(e instanceof Error?e.message:"Could not create workspace.");}finally{setBusy(false);}}
  return <main className="auth-page"><form className="auth-card" onSubmit={submit}><Image src="/marketflow360-logo.svg" alt="MarketFlow360" width={270} height={58} priority/><h1>Create your workspace</h1><p>Start with your team and add records as you go.</p>{error&&<div className="form-error">{error}</div>}{message&&<div className="success-note">{message}</div>}<div className="signup-photo"><div className="photo-edit-wrap"><div className="photo-picker">{profileImage?<img src={profileImage} alt="Profile preview"/>:<span>＋</span>}</div><button type="button" className="photo-edit-button" aria-label="Choose or replace profile photo" title="Choose or replace photo" onClick={()=>fileInput.current?.click()}>✎</button>{profileImage&&<button type="button" className="photo-remove-button" aria-label="Remove profile photo" title="Remove photo" onClick={()=>{setProfileImage("");if(fileInput.current)fileInput.current.value=""}}>×</button>}<input ref={fileInput} className="visually-hidden-file" type="file" accept="image/png,image/jpeg,image/webp" onChange={selectImage}/></div><small>{profileImage?"Edit or remove your photo":"Add a profile photo (optional)"}</small></div><label>Your name<input value={name} onChange={e=>setName(e.target.value)} autoComplete="name" minLength={2} required/></label><label>Work email<input type="email" value={email} onChange={e=>setEmail(e.target.value)} autoComplete="email" required/></label><label>Mobile number <small>Optional</small><span className="phone-fields"><select aria-label="Country calling code" value={countryCode} onChange={e=>setCountryCode(e.target.value)}><option value="+92">🇵🇰 +92 Pakistan</option><option value="+1">🇺🇸 +1 United States/Canada</option><option value="+44">🇬🇧 +44 United Kingdom</option><option value="+91">🇮🇳 +91 India</option><option value="+971">🇦🇪 +971 UAE</option><option value="+966">🇸🇦 +966 Saudi Arabia</option><option value="+61">🇦🇺 +61 Australia</option><option value="+49">🇩🇪 +49 Germany</option></select><input type="tel" value={phone} onChange={e=>setPhone(e.target.value)} autoComplete="tel-national" placeholder="300 1234567"/></span></label><label>Password<PasswordField label="password" value={password} onChange={e=>setPassword(e.target.value)} minLength={10} autoComplete="new-password" required/><small>Use at least 10 characters.</small></label><label>Workspace name<input value={workspaceName} onChange={e=>setWorkspaceName(e.target.value)} minLength={2} required/></label><button className="primary" disabled={busy}>{busy?"Creating…":"Create workspace"}</button><p className="auth-foot">Already registered? <Link href="/login">Sign in</Link></p></form></main>;
}
