ALTER TABLE "Lead" ALTER COLUMN "status" DROP DEFAULT;
ALTER TABLE "Lead" ALTER COLUMN "status" TYPE TEXT USING "status"::text;
ALTER TABLE "Lead" ALTER COLUMN "status" SET DEFAULT 'NEW';
ALTER TABLE "PipelineStage" ALTER COLUMN "key" TYPE TEXT USING "key"::text;
