"use client";
import { FormEvent, useState } from "react";
import { api } from "../api";
import { Attachments, Empty, Frame, Loading, Message, useRows } from "./shared";
type Customer={id:string;name:string;company:string|null;email:string|null;phone:string|null;createdAt:string};
type CustomerProfile=Customer&{notes:string|null;deals:{id:string;title:string;stage:string;amountMinor:number;currency:string}[];tasks:{id:string;title:string;status:string;dueAt:string|null;lead:{name:string}|null}[]};
export function CustomersScreen(){const {rows,loading,error,refresh}=useRows<Customer>("/customers");const [show,setShow]=useState(false);const [name,setName]=useState("");const [company,setCompany]=useState("");const [email,setEmail]=useState("");const [notice,setNotice]=useState("");const [profile,setProfile]=useState<CustomerProfile|null>(null);const [notes,setNotes]=useState("");
 async function add(e:FormEvent){e.preventDefault();try{await api("/customers",{method:"POST",body:JSON.stringify({name,company:company||undefined,email:email||undefined})});setName("");setCompany("");setEmail("");setShow(false);setNotice("Customer saved.");await refresh();}catch(e){setNotice(e instanceof Error?e.message:"Could not save customer.");}}
 async function remove(id:string){if(!confirm("Delete this customer? Related deals and tasks will be unlinked."))return;try{await api(`/customers/${id}`,{method:"DELETE"});await refresh();}catch(e){setNotice(e instanceof Error?e.message:"Could not delete customer.");}}
 async function openProfile(id:string){try{const row=await api<CustomerProfile>(`/customers/${id}`);setProfile(row);setNotes(row.notes||"");}catch(e){setNotice(e instanceof Error?e.message:"Could not load customer.");}}
 async function saveNotes(){if(!profile)return;try{await api(`/customers/${profile.id}`,{method:"PATCH",body:JSON.stringify({notes})});const row=await api<CustomerProfile>(`/customers/${profile.id}`);setProfile(row);setNotice("Customer notes saved.");}catch(e){setNotice(e instanceof Error?e.message:"Could not save notes.");}}
 return <Frame title="Customers" subtitle="Keep customer contacts and company details in one place."><div className="screen-actions"><button className="primary" onClick={()=>setShow(!show)}>＋ Add Customer</button><span className="subtle">{rows.length} customers</span></div>{show&&<form className="record-form" onSubmit={add}><label>Name<input value={name} onChange={e=>setName(e.target.value)} required minLength={2}/></label><label>Company<input value={company} onChange={e=>setCompany(e.target.value)}/></label><label>Email<input value={email} onChange={e=>setEmail(e.target.value)} type="email"/></label><button className="primary">Save customer</button></form>}{notice&&<Message>{notice}</Message>}{error&&<Message error>{error}</Message>}{loading?<Loading/>:rows.length===0?<Empty text="Customer profiles appear here when you add them or convert a lead."/>:<div className="panel record-table"><table><thead><tr><th>Customer</th><th>Company</th><th>Email</th><th>Added</th><th/></tr></thead><tbody>{rows.map(r=><tr key={r.id}><td><button className="text-button" onClick={()=>openProfile(r.id)}>{r.name}</button></td><td>{r.company||"—"}</td><td>{r.email||"—"}</td><td>{new Date(r.createdAt).toLocaleDateString()}</td><td><button className="text-button" onClick={()=>remove(r.id)}>Delete</button></td></tr>)}</tbody></table></div>}{profile&&<div className="modal-backdrop" role="presentation" onClick={e=>{if(e.target===e.currentTarget)setProfile(null);}}><section className="lead-detail" role="dialog" aria-modal="true"><button className="modal-close" onClick={()=>setProfile(null)}>×</button><h2>{profile.name}</h2><p>{profile.company||"Individual customer"} · {profile.email||"No email"}</p><label>Notes<textarea rows={3} value={notes} onChange={e=>setNotes(e.target.value)}/></label><button className="primary" onClick={saveNotes}>Save notes</button><Attachments recordType="CUSTOMER" recordId={profile.id}/><h3>Deals</h3>{profile.deals.length?profile.deals.map(d=><p key={d.id}>{d.title} · {d.currency} {(d.amountMinor/100).toLocaleString()} · {d.stage}</p>):<p>No deals yet.</p>}<h3>Tasks</h3>{profile.tasks.length?profile.tasks.map(t=><p key={t.id}>{t.title} · {t.status}{t.dueAt?` · ${new Date(t.dueAt).toLocaleDateString()}`:""}</p>):<p>No tasks yet.</p>}</section></div>}</Frame>;
}
