"use client";
import { FormEvent, useState } from "react";
import { api } from "../api";
import { Empty, Frame, Loading, Message, useRows } from "./shared";
type Deal={id:string;title:string;amountMinor:number;currency:string;stage:string;expectedAt:string|null;customer:{name:string}|null;lead:{name:string}|null};
export function DealsScreen(){const {rows,loading,error,refresh}=useRows<Deal>("/deals");const [show,setShow]=useState(false);const [title,setTitle]=useState("");const [amount,setAmount]=useState("");const [currency,setCurrency]=useState("PKR");const [notice,setNotice]=useState("");
 async function add(e:FormEvent){e.preventDefault();try{await api("/deals",{method:"POST",body:JSON.stringify({title,amountMinor:Math.round(Number(amount||0)*100),currency})});setTitle("");setAmount("");setShow(false);setNotice("Deal saved.");await refresh();}catch(e){setNotice(e instanceof Error?e.message:"Could not save deal.");}}
 async function stage(id:string,next:string){try{await api(`/deals/${id}`,{method:"PATCH",body:JSON.stringify({stage:next})});await refresh();}catch(e){setNotice(e instanceof Error?e.message:"Could not update deal.");}}
 return <Frame title="Deals" subtitle="Track potential revenue and the next step for each opportunity."><div className="screen-actions"><button className="primary" onClick={()=>setShow(!show)}>＋ Add Deal</button><span className="subtle">{rows.length} deals</span></div>{show&&<form className="record-form" onSubmit={add}><label>Deal title<input value={title} onChange={e=>setTitle(e.target.value)} required minLength={2}/></label><label>Value ({currency})<input type="number" min="0" step="0.01" value={amount} onChange={e=>setAmount(e.target.value)}/></label><label>Currency<select value={currency} onChange={e=>setCurrency(e.target.value)}><option>PKR</option><option>USD</option><option>EUR</option></select></label><button className="primary">Save deal</button></form>}{notice&&<Message>{notice}</Message>}{error&&<Message error>{error}</Message>}{loading?<Loading/>:rows.length===0?<Empty text="Create a deal or convert an interested lead into a customer opportunity."/>:<div className="panel record-table"><table><thead><tr><th>Deal</th><th>Linked to</th><th>Value</th><th>Stage</th><th>Expected close</th></tr></thead><tbody>{rows.map(r=><tr key={r.id}><td><strong>{r.title}</strong></td><td>{r.customer?.name||r.lead?.name||"—"}</td><td>{r.currency} {(r.amountMinor/100).toLocaleString()}</td><td><select value={r.stage} onChange={e=>stage(r.id,e.target.value)}>{["OPEN","PROPOSAL","WON","LOST"].map(s=><option key={s}>{s}</option>)}</select></td><td>{r.expectedAt?new Date(r.expectedAt).toLocaleDateString():"—"}</td></tr>)}</tbody></table></div>}</Frame>;
}
