"use client";
import { ChangeEvent, FormEvent, useEffect, useState } from "react";
import { activeWorkspaceId, api, downloadApiFile } from "../api";
import { Empty, Frame, Loading, Message, useRows } from "./shared";

type Lead={id:string;name:string;email:string|null;phone:string|null;interest:string|null;source:string;status:string;notes:string|null;createdAt:string;assignedToId:string|null;assignedTo:{id:string;name:string}|null};
type Activity={id:string;type:string;message:string;createdAt:string;user:{name:string}|null};
type Member={id:string;user:{id:string;name:string}};
const stages=["NEW","CONTACTED","INTERESTED","PROPOSAL_PENDING","WON","LOST"];
const label=(s:string)=>s.replaceAll("_"," ").toLowerCase().replace(/\b\w/g,c=>c.toUpperCase());

export function LeadsScreen(){const {rows,loading,error,refresh}=useRows<Lead>("/leads");const [view,setView]=useState<"board"|"table">("board");const [form,setForm]=useState(false);const [notice,setNotice]=useState("");const [name,setName]=useState("");const [email,setEmail]=useState("");const [interest,setInterest]=useState("");const [assignee,setAssignee]=useState("");const [members,setMembers]=useState<Member[]>([]);const [selected,setSelected]=useState<Lead|null>(null);const [activities,setActivities]=useState<Activity[]>([]);const [notes,setNotes]=useState("");const [taskTitle,setTaskTitle]=useState("");const [taskDate,setTaskDate]=useState("");
 useEffect(()=>{const workspaceId=activeWorkspaceId();if(workspaceId)api<Member[]>(`/workspaces/${workspaceId}/members`).then(setMembers).catch(()=>undefined)},[]);
 async function add(e:FormEvent){e.preventDefault();setNotice("");try{await api("/leads",{method:"POST",body:JSON.stringify({name,email:email||undefined,interest:interest||undefined,assignedToId:assignee||undefined})});setName("");setEmail("");setInterest("");setAssignee("");setForm(false);setNotice("Lead added.");await refresh();}catch(e){setNotice(e instanceof Error?e.message:"Could not add lead.");}}
 async function assign(row:Lead,userId:string){try{await api(`/leads/${row.id}`,{method:"PATCH",body:JSON.stringify({assignedToId:userId||null})});await refresh()}catch(e){setNotice(e instanceof Error?e.message:"Could not assign lead.")}}
 async function importFile(e:ChangeEvent<HTMLInputElement>){const file=e.target.files?.[0];if(!file)return;try{const lines=(await file.text()).trim().split(/\r?\n/);const parse=(line:string)=>{const out:string[]=[];let value="",quoted=false;for(let i=0;i<line.length;i++){const c=line[i];if(c==='"'&&line[i+1]==='"'&&quoted){value+='"';i++}else if(c==='"')quoted=!quoted;else if(c===","&&!quoted){out.push(value);value=""}else value+=c}out.push(value);return out};const headers=parse(lines.shift()||"").map(x=>x.trim().toLowerCase());const leads=lines.filter(Boolean).map(line=>{const cells=parse(line);return Object.fromEntries(headers.map((h,i)=>[h,cells[i]||undefined])) as {name:string;email?:string;phone?:string;interest?:string;source?:string}}).filter(x=>x.name);const result=await api<{imported:number;skipped:number}>("/leads/import",{method:"POST",body:JSON.stringify({leads})});setNotice(`Imported ${result.imported} leads. Skipped ${result.skipped} duplicates.`);await refresh()}catch(err){setNotice(err instanceof Error?err.message:"Could not import CSV.")}finally{e.target.value=""}}
 async function move(id:string,status:string){try{await api(`/leads/${id}`,{method:"PATCH",body:JSON.stringify({status})});await refresh();}catch(e){setNotice(e instanceof Error?e.message:"Could not update lead.");}}
 async function openLead(row:Lead){setSelected(row);setNotes(row.notes||"");try{setActivities(await api<Activity[]>(`/leads/${row.id}/activities`));}catch(e){setNotice(e instanceof Error?e.message:"Could not load lead activity.");}}
 async function saveNotes(){if(!selected)return;try{await api(`/leads/${selected.id}`,{method:"PATCH",body:JSON.stringify({notes})});await openLead({...selected,notes});setNotice("Notes saved.");await refresh();}catch(e){setNotice(e instanceof Error?e.message:"Could not save notes.");}}
 async function convert(){if(!selected)return;try{await api(`/leads/${selected.id}/convert`,{method:"POST",body:JSON.stringify({})});setNotice("Lead converted to a customer and deal.");setSelected(null);await refresh();}catch(e){setNotice(e instanceof Error?e.message:"Could not convert lead.");}}
 async function archive(){if(!selected)return;if(!confirm("Archive this lead? Its activity and linked tasks will be kept."))return;try{await api(`/leads/${selected.id}`,{method:"DELETE"});setSelected(null);setNotice("Lead archived.");await refresh();}catch(e){setNotice(e instanceof Error?e.message:"Could not archive lead.");}}
 async function addFollowup(e:FormEvent){e.preventDefault();if(!selected)return;try{await api("/tasks",{method:"POST",body:JSON.stringify({title:taskTitle,leadId:selected.id,dueAt:taskDate?new Date(`${taskDate}T12:00:00`).toISOString():undefined})});setTaskTitle("");setTaskDate("");setNotice("Follow-up task added.");}catch(e){setNotice(e instanceof Error?e.message:"Could not add follow-up.");}}
 return <Frame title="Lead Pipeline" subtitle="Track new enquiries, follow-ups and sales progress.">
   <div className="screen-actions"><button className="primary" onClick={()=>setForm(!form)}>{form?"Close":"＋ Add Lead"}</button><label className="csv-import">Import CSV<input type="file" accept=".csv,text/csv" onChange={importFile}/></label><button className="secondary" onClick={()=>void downloadApiFile("/leads/export","marketflow-leads.csv").catch(e=>setNotice(e.message))}>Export CSV</button><div className="view-toggle"><button className={view==="board"?"selected":""} onClick={()=>setView("board")}>Board</button><button className={view==="table"?"selected":""} onClick={()=>setView("table")}>Table</button></div></div>
   {form&&<form className="record-form" onSubmit={add}><label>Name<input value={name} onChange={e=>setName(e.target.value)} required minLength={2}/></label><label>Email<input type="email" value={email} onChange={e=>setEmail(e.target.value)}/></label><label>Interest<input value={interest} onChange={e=>setInterest(e.target.value)}/></label><label>Assigned to<select value={assignee} onChange={e=>setAssignee(e.target.value)}><option value="">Unassigned</option>{members.map(m=><option key={m.id} value={m.user.id}>{m.user.name}</option>)}</select></label><button className="primary">Save lead</button></form>}
   {notice&&<Message>{notice}</Message>}{error&&<Message error>{error}</Message>}{loading?<Loading/>:rows.length===0?<Empty text="Add a lead or import your first enquiry."/>:view==="board"?<div className="lead-board">{stages.map(stage=><section className="stage-column" key={stage}><h2>{label(stage)} <span>{rows.filter(r=>r.status===stage).length}</span></h2>{rows.filter(r=>r.status===stage).map(row=><article className="lead-card" key={row.id}><strong>{row.name}</strong><small>{row.interest||"No interest recorded"}</small><small>{row.email||row.phone||"No contact details"}</small><select aria-label={`Assign ${row.name}`} value={row.assignedToId||""} onChange={e=>void assign(row,e.target.value)}><option value="">Unassigned</option>{members.map(m=><option key={m.id} value={m.user.id}>{m.user.name}</option>)}</select><button className="text-button" onClick={()=>openLead(row)}>View details</button><select aria-label={`Move ${row.name} to stage`} value={row.status} onChange={e=>move(row.id,e.target.value)}>{stages.map(s=><option key={s} value={s}>{label(s)}</option>)}</select></article>)}</section>)}</div>:<div className="panel record-table"><table><thead><tr><th>Name</th><th>Interest</th><th>Source</th><th>Owner</th><th>Stage</th><th>Created</th><th/></tr></thead><tbody>{rows.map(row=><tr key={row.id}><td><button className="text-button" onClick={()=>openLead(row)}>{row.name}</button><small>{row.email}</small></td><td>{row.interest||"—"}</td><td>{label(row.source)}</td><td><select aria-label={`Assign ${row.name}`} value={row.assignedToId||""} onChange={e=>void assign(row,e.target.value)}><option value="">Unassigned</option>{members.map(m=><option key={m.id} value={m.user.id}>{m.user.name}</option>)}</select></td><td><select value={row.status} onChange={e=>move(row.id,e.target.value)}>{stages.map(s=><option key={s} value={s}>{label(s)}</option>)}</select></td><td>{new Date(row.createdAt).toLocaleDateString()}</td><td><button className="text-button" onClick={()=>openLead(row)}>Details</button></td></tr>)}</tbody></table></div>}
   {selected&&<div className="modal-backdrop" role="presentation" onClick={e=>{if(e.target===e.currentTarget)setSelected(null);}}><section className="lead-detail" role="dialog" aria-modal="true" aria-labelledby="lead-detail-title"><button className="modal-close" onClick={()=>setSelected(null)} aria-label="Close lead details">×</button><h2 id="lead-detail-title">{selected.name}</h2><p>{selected.email||"No email"} · {selected.phone||"No phone"}</p><p><b>Interest:</b> {selected.interest||"Not set"} · <b>Source:</b> {label(selected.source)}</p><label>Notes<textarea value={notes} onChange={e=>setNotes(e.target.value)} rows={3}/></label><button className="primary" onClick={saveNotes}>Save notes</button><h3>Activity</h3><div className="activity-list">{activities.map(a=><p key={a.id}><b>{a.message}</b><small>{a.user?.name||"Team"} · {new Date(a.createdAt).toLocaleString()}</small></p>)}</div><form className="followup-form" onSubmit={addFollowup}><h3>Schedule follow-up</h3><input value={taskTitle} onChange={e=>setTaskTitle(e.target.value)} placeholder="Call to discuss course details" required/><input type="date" value={taskDate} onChange={e=>setTaskDate(e.target.value)}/><button className="primary">Add follow-up</button></form>{!['WON','LOST'].includes(selected.status)&&<button className="convert-button" onClick={convert}>Convert to customer and deal</button>}<button className="text-button archive-button" onClick={archive}>Archive lead</button></section></div>}
 </Frame>;
}
