"use client";
import { FormEvent, useEffect, useState } from "react";
import { api } from "../api";
import { Frame, Loading, Message } from "./shared";

type Connection={id:string;provider:string;label:string;status:string;webhookKey:string};
export function IntegrationsScreen(){const [rows,setRows]=useState<Connection[]|null>(null),[provider,setProvider]=useState("WEBHOOK"),[label,setLabel]=useState("Website form"),[error,setError]=useState("");async function load(){try{setRows(await api<Connection[]>("/integrations"))}catch(e){setError(e instanceof Error?e.message:"Could not load integrations.")}}useEffect(()=>{void load()},[]);async function add(e:FormEvent){e.preventDefault();setError("");try{await api("/integrations",{method:"POST",body:JSON.stringify({provider,label})});await load()}catch(x){setError(x instanceof Error?x.message:"Could not add integration.")}}async function remove(id:string){await api(`/integrations/${id}`,{method:"DELETE"});await load()}return <Frame title="Integrations" subtitle="Receive leads from websites and other tools through a workspace-specific webhook.">{error&&<Message error>{error}</Message>}<form className="form-grid" onSubmit={add}><label>Provider<select value={provider} onChange={e=>setProvider(e.target.value)}><option>WEBHOOK</option></select></label><label>Connection name<input value={label} onChange={e=>setLabel(e.target.value)} required minLength={2}/></label><button className="primary">Create connection</button></form>{rows===null?<Loading/>:<div className="card-grid">{rows.map(x=><article className="card" key={x.id}><h3>{x.label}</h3><p>{x.provider} · {x.status}</p><code className="integration-url">POST /api/v1/webhooks/{x.webhookKey}/leads</code><p>Send JSON with a name and optional email, phone, interest.</p><button onClick={()=>void remove(x.id)}>Disconnect</button></article>)}</div>}<p>Social, messaging and ad account OAuth adapters require provider credentials and are not enabled yet.</p></Frame>}

type AssistantMessage={id:number;role:"assistant"|"user";content:string};
const starterQuestions=["Which leads should I follow up with today?","Show me overdue tasks.","Summarize my deal pipeline and value.","Which lead sources bring the most enquiries?"];
export function AssistantScreen(){const [question,setQuestion]=useState("");const [messages,setMessages]=useState<AssistantMessage[]>([{id:0,role:"assistant",content:"Hi! I can help you decide what to work on using this workspace’s leads, tasks, deals and campaigns. Pick a question below or ask your own."}]);const [suggestions,setSuggestions]=useState(starterQuestions);const [busy,setBusy]=useState(false);const [error,setError]=useState("");async function ask(text:string){const prompt=text.trim();if(!prompt||busy)return;setQuestion("");setError("");setMessages(current=>[...current,{id:Date.now(),role:"user",content:prompt}]);setBusy(true);try{const result=await api<{answer:string;suggestions?:string[]}>("/assistant/ask",{method:"POST",body:JSON.stringify({question:prompt})});setMessages(current=>[...current,{id:Date.now()+1,role:"assistant",content:result.answer}]);if(result.suggestions?.length)setSuggestions(result.suggestions)}catch(e){setError(e instanceof Error?e.message:"Could not get a workspace suggestion.")}finally{setBusy(false)}}function submit(e:FormEvent){e.preventDefault();void ask(question)}return <Frame title="Workspace Assistant" subtitle="Ask a question or choose a suggestion to get a data-backed next step."><section className="assistant-chat"><div className="assistant-suggestions"><strong>Try asking</strong>{suggestions.map(prompt=><button type="button" key={prompt} disabled={busy} onClick={()=>void ask(prompt)}>{prompt}<span>→</span></button>)}</div><div className="assistant-conversation" aria-live="polite">{messages.map(message=><article key={message.id} className={`assistant-message ${message.role}`}><b>{message.role==="assistant"?"MarketFlow Assistant":"You"}</b><p>{message.content}</p></article>)}{busy&&<article className="assistant-message assistant"><b>MarketFlow Assistant</b><p className="assistant-thinking">Checking your workspace…</p></article>}</div>{error&&<Message error>{error}</Message>}<form className="assistant-composer" onSubmit={submit}><textarea value={question} onChange={e=>setQuestion(e.target.value)} onKeyDown={e=>{if(e.key==="Enter"&&!e.shiftKey){e.preventDefault();void ask(question)}}} rows={2} maxLength={1000} placeholder="Ask about leads, tasks, deals, sources or campaigns…" aria-label="Your question"/><button className="primary" disabled={busy||question.trim().length<3}>{busy?"Thinking…":"Ask assistant"}</button></form><small className="assistant-data-note">Answers use records from the selected workspace. External AI service is not connected.</small></section></Frame>}

type PlanResult={subscription:{plan:string;status:string;periodEnd:string|null};plans:{id:string;name:string;limits:{seats:number;leads:number}}[];billingConfigured:boolean;billingPortalUrl:string|null};
export function PlansScreen(){const [data,setData]=useState<PlanResult|null>(null),[error,setError]=useState("");useEffect(()=>{api<PlanResult>("/plans").then(setData).catch(e=>setError(e instanceof Error?e.message:"Could not load plans."))},[]);return <Frame title="Plans & Billing" subtitle="Review workspace plan limits and billing status.">{error&&<Message error>{error}</Message>}{!data?<Loading/>:<><article className="card"><h2>{data.subscription.plan} plan · {data.subscription.status}</h2><p>Payment provider: {data.billingConfigured?"configured":"not configured"}</p>{data.billingPortalUrl&&<a className="button primary" href={data.billingPortalUrl}>Open billing portal</a>}</article><div className="card-grid">{data.plans.map(p=><article className="card" key={p.id}><h3>{p.name}</h3><p>Up to {p.limits.seats} seats and {p.limits.leads.toLocaleString()} leads</p>{p.id===data.subscription.plan&&<strong>Current plan</strong>}</article>)}</div><p>Plan catalog is informational until a payment provider is configured. No charge or plan upgrade is processed in this MVP.</p></>}</Frame>}

type AdminSummary={users:number;workspaces:number;leads:number;plans:{plan:string;_count:{_all:number}}[]};
export function PlatformAdminScreen(){const [data,setData]=useState<AdminSummary|null>(null),[error,setError]=useState("");useEffect(()=>{api<AdminSummary>("/platform-admin/overview").then(setData).catch(e=>setError(e instanceof Error?e.message:"Platform admin access unavailable."))},[]);return <Frame title="Platform Administration" subtitle="Restricted service-wide account totals.">{error&&<Message error>{error}</Message>}{data&&<div className="card-grid">{[["Users",data.users],["Workspaces",data.workspaces],["Leads",data.leads]].map(([a,b])=><article className="card" key={String(a)}><h2>{a}</h2><strong>{b}</strong></article>)}<article className="card"><h3>Workspaces by plan</h3>{data.plans.map(x=><p key={x.plan}>{x.plan}: {x._count._all}</p>)}</article></div>}</Frame>}

export function AuditScreen(){const [rows,setRows]=useState<any[]|null>(null),[error,setError]=useState("");useEffect(()=>{api<any[]>("/audit").then(setRows).catch(e=>setError(e instanceof Error?e.message:"Could not load audit log."))},[]);return <Frame title="Security Audit Log" subtitle="Recent integration and inbound webhook changes.">{error&&<Message error>{error}</Message>}{rows===null?<Loading/>:rows.length===0?<p>No events recorded yet.</p>:<div className="card">{rows.map(r=><p key={r.id}><strong>{r.action}</strong> · {r.entity} · {new Date(r.createdAt).toLocaleString()}</p>)}</div>}</Frame>}
