"use client";
import { FormEvent, useState } from "react";
import { api } from "../api";
import { Empty, Frame, Loading, Message, useRows } from "./shared";
type Task={id:string;title:string;description:string|null;status:string;priority:string;dueAt:string|null;lead:{name:string}|null;customer:{name:string}|null};
type Comment={id:string;body:string;user:{name:string};createdAt:string};
function TaskCalendar({tasks}:{tasks:Task[]}){const [month,setMonth]=useState(()=>new Date(new Date().getFullYear(),new Date().getMonth(),1));const first=new Date(month.getFullYear(),month.getMonth(),1);const start=new Date(first);start.setDate(first.getDate()-((first.getDay()+6)%7));const days=Array.from({length:42},(_,i)=>new Date(start.getFullYear(),start.getMonth(),start.getDate()+i));const key=(d:Date)=>`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,"0")}-${String(d.getDate()).padStart(2,"0")}`;return <section className="panel task-calendar"><div className="calendar-heading"><button className="secondary" onClick={()=>setMonth(new Date(month.getFullYear(),month.getMonth()-1,1))}>‹</button><h2>{month.toLocaleDateString(undefined,{month:"long",year:"numeric"})}</h2><button className="secondary" onClick={()=>setMonth(new Date(month.getFullYear(),month.getMonth()+1,1))}>›</button></div><div className="calendar-grid">{["Mon","Tue","Wed","Thu","Fri","Sat","Sun"].map(day=><b className="calendar-weekday" key={day}>{day}</b>)}{days.map(day=>{const records=tasks.filter(t=>t.dueAt&&key(new Date(t.dueAt))===key(day));return <div className={`calendar-day ${day.getMonth()!==month.getMonth()?"outside":""}`} key={key(day)}><b>{day.getDate()}</b>{records.slice(0,3).map(task=><span className={`calendar-task ${task.status==="DONE"?"complete":""}`} title={task.title} key={task.id}>{task.title}</span>)}{records.length>3&&<small>+{records.length-3} more</small>}</div>})}</div></section>}
function TaskThread({id}:{id:string}){const [rows,setRows]=useState<Comment[]>([]);const [body,setBody]=useState("");const [open,setOpen]=useState(false);const [error,setError]=useState("");async function load(){try{setRows(await api<Comment[]>(`/tasks/${id}/comments`));setError("");}catch(e){setError(e instanceof Error?e.message:"Could not load comments.");}}async function add(e:FormEvent){e.preventDefault();try{await api(`/tasks/${id}/comments`,{method:"POST",body:JSON.stringify({body})});setBody("");await load();}catch(e){setError(e instanceof Error?e.message:"Could not add comment.");}}return <details className="task-thread" onToggle={e=>{const next=(e.currentTarget as HTMLDetailsElement).open;setOpen(next);if(next)void load();}}><summary>Comments</summary>{open&&<div className="thread-content">{error&&<small className="thread-error">{error}</small>}{rows.map(c=><p key={c.id}><b>{c.user.name}</b> · {new Date(c.createdAt).toLocaleDateString()}<br/>{c.body}</p>)}<form onSubmit={add}><input value={body} onChange={e=>setBody(e.target.value)} placeholder="Add a comment…" required maxLength={2000}/><button className="text-button">Send</button></form></div>}</details>}
export function TasksScreen(){const {rows,loading,error,refresh}=useRows<Task>("/tasks");const [show,setShow]=useState(false);const [calendar,setCalendar]=useState(false);const [title,setTitle]=useState("");const [dueAt,setDueAt]=useState("");const [notice,setNotice]=useState("");
 async function add(e:FormEvent){e.preventDefault();try{await api("/tasks",{method:"POST",body:JSON.stringify({title,dueAt:dueAt?new Date(`${dueAt}T12:00:00`).toISOString():undefined})});setTitle("");setDueAt("");setShow(false);setNotice("Task created.");await refresh();}catch(e){setNotice(e instanceof Error?e.message:"Could not create task.");}}
 async function status(id:string,next:string){try{await api(`/tasks/${id}`,{method:"PATCH",body:JSON.stringify({status:next})});await refresh();}catch(e){setNotice(e instanceof Error?e.message:"Could not update task.");}}
 return <Frame title="Tasks & Follow-ups" subtitle="Keep promised calls and team work visible and up to date."><div className="screen-actions"><button className="primary" onClick={()=>setShow(!show)}>＋ Add Task</button><div className="view-toggle"><button className={!calendar?"selected":""} onClick={()=>setCalendar(false)}>List</button><button className={calendar?"selected":""} onClick={()=>setCalendar(true)}>Calendar</button></div><span className="subtle">{rows.filter(r=>r.status!=="DONE").length} open · {rows.filter(r=>r.status!=="DONE"&&r.dueAt&&new Date(r.dueAt)<new Date()).length} overdue</span></div>{show&&<form className="record-form" onSubmit={add}><label>Task<input value={title} onChange={e=>setTitle(e.target.value)} required minLength={2}/></label><label>Due date<input type="date" value={dueAt} onChange={e=>setDueAt(e.target.value)}/></label><button className="primary">Save task</button></form>}{notice&&<Message>{notice}</Message>}{error&&<Message error>{error}</Message>}{loading?<Loading/>:rows.length===0?<Empty text="Add a follow-up or create one from a lead or customer."/>:calendar?<TaskCalendar tasks={rows}/>:<div className="panel record-table"><table><thead><tr><th>Task</th><th>Related record</th><th>Priority</th><th>Due</th><th>Status</th></tr></thead><tbody>{rows.map(r=><tr key={r.id}><td><strong>{r.title}</strong><small>{r.description}</small><TaskThread id={r.id}/></td><td>{r.lead?.name||r.customer?.name||"—"}</td><td><span className={`badge ${r.priority.toLowerCase()}`}>{r.priority}</span></td><td>{r.dueAt?new Date(r.dueAt).toLocaleDateString():"—"}</td><td><select value={r.status} onChange={e=>status(r.id,e.target.value)}>{["OPEN","IN_PROGRESS","DONE"].map(s=><option key={s}>{s}</option>)}</select></td></tr>)}</tbody></table></div>}</Frame>;
}
