"use client";
import { FormEvent, useEffect, useState } from "react";
import { api, activeWorkspaceId } from "../api";
import { Empty, Frame, Loading, Message } from "./shared";
type Member={id:string;role:string;user:{name:string;email:string}};
const roles=["ADMIN","MARKETING_MANAGER","SALES_AGENT","CONTENT_CREATOR","APPROVER","ANALYST","CLIENT_VIEWER"];
export function TeamScreen(){const [members,setMembers]=useState<Member[]>([]);const [loading,setLoading]=useState(true);const [error,setError]=useState("");const [email,setEmail]=useState("");const [role,setRole]=useState("SALES_AGENT");const [invite,setInvite]=useState("");const [inviteMessage,setInviteMessage]=useState("");const workspaceId=activeWorkspaceId();
 async function refresh(){if(!workspaceId)return;setLoading(true);try{setMembers(await api<Member[]>(`/workspaces/${workspaceId}/members`));setError("");}catch(e){setError(e instanceof Error?e.message:"Could not load team.");}finally{setLoading(false);}}
 useEffect(()=>{void refresh();},[workspaceId]);
 async function send(e:FormEvent){e.preventDefault();setInvite("");setInviteMessage("");try{const result=await api<{acceptUrl?:string;delivery:string}>(`/workspaces/${workspaceId}/invitations`,{method:"POST",body:JSON.stringify({email,role})});setInvite(result.acceptUrl||"");setInviteMessage(result.delivery==="Email sent."?"Invitation email sent.":"Demo invitation link is ready.");setEmail("");await refresh();}catch(e){setError(e instanceof Error?e.message:"Could not create invitation.");}}
 async function change(id:string,next:string){try{await api(`/workspaces/${workspaceId}/members/${id}`,{method:"PATCH",body:JSON.stringify({role:next})});await refresh();}catch(e){setError(e instanceof Error?e.message:"Could not update role.");}}
 async function remove(id:string){if(!confirm("Remove this member from the workspace?"))return;try{await api(`/workspaces/${workspaceId}/members/${id}`,{method:"DELETE"});await refresh();}catch(e){setError(e instanceof Error?e.message:"Could not remove member.");}}
 return <Frame title="Team & Access" subtitle="Manage workspace members and give each person only the access they need."><div className="panel team-panel"><h2>Invite a teammate</h2><p>Configured email is sent automatically; local mode gives you a shareable link.</p><form className="record-form" onSubmit={send}><label>Email<input type="email" value={email} onChange={e=>setEmail(e.target.value)} required/></label><label>Role<select value={role} onChange={e=>setRole(e.target.value)}>{roles.map(r=><option key={r} value={r}>{r.replaceAll("_"," ")}</option>)}</select></label><button className="primary">Create invitation</button></form>{inviteMessage&&<Message>{inviteMessage}{invite&&<> Invite link: <a className="demo-link" href={invite}>{invite}</a></>}</Message>}</div>{error&&<Message error>{error}</Message>}<h2 className="section-title">Workspace members</h2>{loading?<Loading/>:members.length===0?<Empty text="No members found."/>:<div className="panel record-table"><table><thead><tr><th>Name</th><th>Email</th><th>Role</th><th/></tr></thead><tbody>{members.map(m=><tr key={m.id}><td><strong>{m.user.name}</strong></td><td>{m.user.email}</td><td>{m.role==="OWNER"?<span className="badge">Owner</span>:<select value={m.role} onChange={e=>change(m.id,e.target.value)}>{roles.map(r=><option key={r} value={r}>{r.replaceAll("_"," ")}</option>)}</select>}</td><td>{m.role!=="OWNER"&&<button className="text-button" onClick={()=>remove(m.id)}>Remove</button>}</td></tr>)}</tbody></table></div>}</Frame>;
}
